### ISSUE TITLE
Sonosetup text

### ISSUE THREAD

**Issue by cewall** [NESCent/feedingdb#22]
Add descriptive text somewhere on this [page](https://feedexp.org/admin/feed/sonosetup/119/)
New Text: If using sonomicrometry on non-muscle tissue, please stop with Sono Setup and use the Other Setup.

**Comment by hlapp** [comment]
@cewall we'll need to identify more precisely where this should go.

**Comment by cewall** [comment]
I looked at the page, and think it should go in smaller text directly to the right of or below (whichever fits better - probably to the right of) the "Edit Sono Setup" text at the very top of the edit page [here](https://feedexp.org/admin/feed/sonosetup/119/edit/)

**Comment by hlapp** [comment]
We'll have to confer with SquishyMedia on how to accomplish this, because this is not a label or help text change. I also doubt that this is really what we want - wouldn't what you suggest be applicable only _adding_ sono setup, but not to _editing_ it (assuming that where sono records exist already, they do so correctly, and hence this warning would only be confusing).

**Comment by cewall** [comment]
It is applicable to BOTH adding a Sono setup and editing an existing Sono setup (i.e., in either case, an uploader in this situation would be planning to add new raw data from a non-muscle anatomical location).

I would say that it could (though admittedly not optimally) be put in now as a help text. 

In FEED3, there MFMO will hopefully be fine-grained enough for bone and connective tissue that we can include those anatomical locations in the original Sono Setup.

**Comment by hlapp** [comment]
@cewall: I figured out how to add it as a help text for the setup as was your original idea.
